### ISSUE TITLE
does not honor cortex-debug.armToolchainPath

### ISSUE THREAD

**Issue by akohlsmith** [bmd-studio/stm32-for-vscode#1]
This extension relies on cortex-debug, which has an option for specifying the path to the cross compiler.

It does not appear that this extension uses this setting to find the toolchain, instead relying on the toolchain to be on the system path.

I'm not sure if this is a bug or a wishlist item at this point.

**Comment by jortbmd** [comment]
Hi Andrew,

It is something I also wish to implement. This will be included in the next version.
