### ISSUE TITLE
Command stm32-for-vscode... not found

### ISSUE THREAD

**Issue by josueportiz** [bmd-studio/stm32-for-vscode#110]
Dear all,

I haven't be able to get the extension run. After the installation the logo doesn't appear in the sidebar. If I run commands (Ctrl+Shift+P) I get different errors.

-   If I run "stm32-for-vscode.checkBuildTools" it raises an error: "**command for stm32-for-vscode.checkBuildTools not found**".
-   If I type "STM32: Open the SMT32 for VSCode extension" I get the following error: "**The "path" argument must be of type string. Received an instance of String**". The same occurs with other commands.
-   The file "**STM32-for-VSCode.config.yaml**" does not exist. 

Setup:
-    OS: Ubuntu 20.04
-    VSCode version: 1.68.0
-    Node version: v16.15.1
-    Version: stm32-for-vscode-3.2.1

Thank you very much for your time.
Kind regards.

**Comment by jortbmd** [comment]
Thanks for opening up an issue for this.
Could it be that you are not in an active folder/workspace? As the extension will only startup when it sees a file with the .ioc extension or the stm32-for-vscode.config.yaml file.
If not let me know, then I can look into it.

**Comment by josueportiz** [comment]
Thank you for your kind replay.

That was my fault. If double checked it in two different OS. It works. Thank you for the point.

Kind regards.
