### ISSUE TITLE
undefined reference to _exit _kill and _getpid

### ISSUE THREAD

**Issue by JudgeBeeb** [bmd-studio/stm32-for-vscode#120]
Building a C++ project failed due to `undefined references to _exit _kill and  _getpid`. This happens using code generated by CubeMX without any modifications to the code other than renaming main.c to main.cpp.

Based on what I read [here](https://www.openstm32.org/forumthread2449#threadId2453), I changed the linker flags in STM32-for-VSCode.config.yaml by adding -specs=nosys.specs. This solved the problem.

Understanding the nature of this problem is very much above my pay-grade. But hopefully these comments are of assistance. 

And thank you very much for an awesome extension.

**Comment by jortbmd** [comment]
Thank you for sharing the solution! This is indeed the correct way to prevent that kind of error.
