### ISSUE TITLE
Does you plug integrate an MX clocks and I/O graphical interface

### ISSUE THREAD

**Issue by BitLoose** [bmd-studio/stm32-for-vscode#124]
Would like to know if STMs graphical interface is supported from the .ioc file?  Using it to set clocks and I/O and then generate the setup code is the best feature of STM32CubeIDE, though the underlying Eclipse IDE is very limited in most areas and a bit unstable.

**Comment by jortbmd** [comment]
Hi. Yes it does! CubeMX is not integrate in the app but you can generate the set-up code and use that when using STM32 For VSCode. Look at the README for instructions. You can find it here: https://github.com/bmd-studio/stm32-for-vscode/blob/master/README.md
tldr: select generate as makefile in project manager.
