### ISSUE TITLE
arm-none-eabi-gcc.exe application error 

### ISSUE THREAD

**Issue by tfeitian** [bmd-studio/stm32-for-vscode#14]
The arm-none-eabi-gcc will run into error when the default shell of VScode is cmd.exe.After changing the default shell to bash.exe fixed the issue.
![error](https://user-images.githubusercontent.com/8262776/72219903-22906680-3586-11ea-8d60-2a7e41275b56.jpg)

**Comment by jortbmd** [comment]
Sorry for the late comment. Thanks for reporting. I guess it is an issue related to your specific system. However could you perhaps translate the error message above just to be sure?

**Comment by jortbmd** [comment]
Closed because of inactivity. Should problem persist please let me know.
