### ISSUE TITLE
ST button not showing up 

### ISSUE THREAD

**Issue by DiegoTheMod** [bmd-studio/stm32-for-vscode#140]
Hi, I have just started trying to use the software but I can't get it to recognize my project files and start stm32 for vscode.
![Screenshot 2023-02-13 102415](https://user-images.githubusercontent.com/41545685/218528423-335dc0ac-9640-41e0-9b25-381b99ac1dcf.png)

**Comment by jortbmd** [comment]
Hi!
Thanks for opening up an issue for this. Could you tell me what kind of files are in your workspace? It generally looks for a .ioc file on start-up. Should that fail there is also a command which you can use (use ctrl/cmd + shift + p to open up the command pop-up). The command is: "STM32: Open the STM32 for VSCode extension".
Hope this helps. Please let me know if the issue persists.

**Comment by jortbmd** [comment]
Will close this issue due to inactivity. If the issue persists feel free to re-open up this issue again.
