### ISSUE TITLE
Certificate_expiration

### ISSUE THREAD

**Issue by vincent01720** [bmd-studio/stm32-for-vscode#141]
Hi,
I've encountered an issue about a certificate expiration, is there anything from my side I can do to fix it?
<img width="1570" alt="Screenshot 2023-02-18 at 11 55 01 PM" src="https://user-images.githubusercontent.com/64711511/219923103-c8f12be9-bbb0-4257-b8bd-6fd90690eb30.png">

**Comment by mjerjawi** [comment]
I had a similar issue seems like your installation failed half way through try to delete everything in C:\Users\[USERNAME]\AppData\Roaming\Code\User\globalStorage\bmd.stm32-for-vscode
it may resolve your issue

**Comment by jortbmd** [comment]
Hi!
Thanks for opening up an issue. What mjerjawi said might solve the issue as an old installation of node maybe present there which  has an old certificate. If the issue persists please let me know.

**Comment by jortbmd** [comment]
Quick update I have updated the installation flow for tools, which should remove any old node installation which could give the above behaviour.
Due to inactivity I will close this issue. Should it persist feel free to re-open up the issue and I can look into it a bit further.
