### ISSUE TITLE
ASM_SOURCES not included in OBJECTS

### ISSUE THREAD

**Issue by Flo2410** [bmd-studio/stm32-for-vscode#150]
As mentioned by @has213, the ASM_SOURCES are no longer included in the OBJECTS after the last update with the fix for #143.

Adding ``OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))`` fixed the issue.

>Hi jortbmd,  
>
>Maybe there is an Error in the makefile generation  
>
>![image](https://user-images.githubusercontent.com/124668876/228526418-cf431316-73d7-4a6f-b863-96e07de1900b.png)
>![image](https://user-images.githubusercontent.com/124668876/228526629-1a8bdbf5-fdd2-4919-b5e7-f7328c946e16.png)
>
>There are no UPPER_CASE_ASM_SOURCES and LOWER_CASE_ASM_SOURCES only ASM_SOURCES, which will not be included in OBJECTS

_Originally posted by @has213 in https://github.com/bmd-studio/stm32-for-vscode/issues/143#issuecomment-1488459723_

**Comment by m4tto** [comment]
I have the same issue. The startup script is not compiled and the generated elf file is basically empty.

**Comment by jortbmd** [comment]
Thanks for opening up this issue! I am currently on it somehow this got through the whole pipeline without triggering errors. Just tested the fix and will try to resolve this ASAP. Will keep you posted

**Comment by jortbmd** [comment]
Just published the new release. Could everybody please checks that this resolves the issue? Also thanks for notifying me this quickly!

**Comment by Flo2410** [comment]
Yes, it works.  Thanks!

FYI: The comment ``# list of ASM program objects`` is duplicated.

**Comment by jortbmd** [comment]
Great to hear that it is working. @Flo2410 Thanks for pointing out the double comment. For now I will fix this in an upcoming release. 
As it is working now I will close this issue. Should any of you experience a new issue or wants a feature request don't hesitate to open up a new issue.
