### ISSUE TITLE
Default build configuration keeps popping up

### ISSUE THREAD

**Issue by knandersen** [bmd-studio/stm32-for-vscode#17]
_Disclaimer: I'm very new to using VSCode for embedded work, and still a relative novice when it comes to VSCode._

I want to use a different configuration than the default build configuration which uses openocd. But every time I add my own configuration, the default one keeps getting restored and added. And problem is that for some reason, the `> Build and flash to an STM32 platform`-command insists on using the default configuration rather than my custom one.

Have I missed something? Is there a way to just have my configuration in there, or defining which configuration the `> Build and flash to an STM32 platform`-command should use? Thanks!

What I want:

```
{
  "configurations": [
    {
      "cwd": "${workspaceRoot}",
      "executable": "./build/MicButton.elf",
      "name": "Debug STM32 Using ST-Link",
      "request": "launch",
      "type": "cortex-debug",
      "servertype": "stutil"
    }
  ]
}
```

what I keep getting:

```
{
  "configurations": [
    {
      "cwd": "${workspaceRoot}",
      "executable": "./build/MicButton.elf",
      "name": "Debug STM32 Using ST-Link",
      "request": "launch",
      "type": "cortex-debug",
      "servertype": "stutil"
    },
    {
      "showDevDebugOutput": true,
      "cwd": "${workspaceRoot}",
      "executable": "./build/MicButton.elf",
      "name": "Debug STM32",
      "request": "launch",
      "type": "cortex-debug",
      "servertype": "openocd",
      "preLaunchTask": "Build STM",
      "device": "stlink",
      "configFiles": [
        "interface/stlink-v2-1.cfg",
        "target/false"
      ]
    }
  ]
}
```

**Comment by jortbmd** [comment]
Hi.

You can use both if you look at the debugger you would see two configurations. One is yours the other is from STM32 For VSCode. You can use f5 to start a debug session. Do keep in mind that it does not build before debugging in your configuration. You might want to add the

**Comment by knandersen** [comment]
Sorry I forgot to reply to this, @jortbmd ! Thanks for providing assistance on this, I didn't really have a good grip on VSCode or extension settings at the time, so this helped a lot. Also thanks for providing a great tool!
