### ISSUE TITLE
File paths which include `#` character break the generated Makefile

### ISSUE THREAD

**Issue by DeflateAwning** [bmd-studio/stm32-for-vscode#203]
Shocking I came across this, but file paths which contain a `#` symbol (for example, in the STM32 ST Cryptolib library: `./Middlewares/ST/ST_Cryptolib/Inc/RSA/PKCS#1v15/rsa_pkcs1v15.h`). 

I think it's an easy fix, where the `#` symbol needs to be replaced with `\#`.

Would you accept a fix for just this and publish a release with just this change?

**Comment by jortbmd** [comment]
Thanks for noticing these things and the willingness to help. Yes I would accept a fix and publish the release. There have been a couple of hot fixes I have been putting off for a new version but this might be a nice reason to do a tiny version bump in between.

**Comment by DeflateAwning** [comment]
Should I branch off of main? Is that where the release will be tagged from?

**Comment by DeflateAwning** [comment]
Would really appreciate if you could tag a release of this pretty soon! This will be very helpful to us.

**Comment by jortbmd** [comment]
Yes. Will run some tests today and if all looks good will release a new minor version.
I was also wondering if you could provide a small project which uses and compiles the crypto project, which fails now and succeeds on your change. This way I can add it to the test suite, to prevent regression of this in the future.

**Comment by jortbmd** [comment]
New version 3.2.8 is published!
