### ISSUE TITLE
Buggy IntelliSense

### ISSUE THREAD

**Issue by robokamran** [bmd-studio/stm32-for-vscode#25]
I'm new to VSCode in windows. Does anyone have a serious issue with the IntelliSense or is it just me? for example if I use uint32_t in my code, the whole code from that line will mess up. Yet it is ok with uint8_t :)) my `c_cpp_properties.json` for Microsoft C/C++ plugin is like this:

`
{
  "configurations": [
    {
      "name": "STM32",
      "includePath": [
        "Drivers/CMSIS/Device/ST/STM32F3xx/Include",
        "Drivers/CMSIS/Include",
        "Drivers/STM32F3xx_HAL_Driver/Inc",
        "Drivers/STM32F3xx_HAL_Driver/Inc/Legacy",
        "Inc"
      ],
      "defines": ["STM32F303xE", "USE_HAL_DRIVER"],
      "compilerPath": "arm-none-eabi-gcc",
      "cStandard": "c11",
      "cppStandard": "c++11"
    }
  ],
  "version": 4
}
`

The code compiles successfully, the case is with the IntelliSense. Also I get an error for `"compilerPath": "arm-none-eabi-gcc"` which says `Cannot find "arm-none-eabi-gcc"`. If it is the problem how can this be solved generally?

![image](https://user-images.githubusercontent.com/8957516/87950163-2e705e80-cabc-11ea-9f2c-83fe59570c77.png)

![image](https://user-images.githubusercontent.com/8957516/87969235-f9bdd080-cad6-11ea-9fd5-aa57835f54de.png)

**Comment by jortbmd** [comment]
Hi thanks for opening an issue.

I checked myself and I also get the same issue for the compilerPath. It seems that it needs an absolute path. Will try to include this in a next release.

Despite this it should still function. I do not know about the uint8_t vs uint32_t but when I include stdint.h all works as expected.
Did you include the stdint.h header?

**Comment by robokamran** [comment]
Hi @jortbmd and thanks for noting this issue.
The project is generated by _STM32CubeMX_ and all the necessary headers are included in cascade (the code compiles successfully).
I have set an absolute path for `compilerPath` manually and the problem got fixed 👍. It seems that due to the nested includes and specific macros in them, the IntelliSense gets confused and it substantially needs the correct `compilerPath` to behave :))

**Comment by jortbmd** [comment]
This is fixed in version 2.2.2 so I hope it helps and therefore I am closing this issue.
