### ISSUE TITLE
Not linking with g++ when compiling c++

### ISSUE THREAD

**Issue by jortbmd** [bmd-studio/stm32-for-vscode#32]
Hi guys :)

actually one addition to this. The fix described works well for compiling, but e.g. including the <string> cpp standard library, in my case I still got an error.

This is due to the compiling goes with g++, but not the final linking.
In the file STM32Make.make, around Line 215:

`$(CC) $(OBJECTS) $(LDFLAGS) -o $@`

should be changed to

`$(CXX) $(OBJECTS) $(LDFLAGS) -o $@`

when compiling with cpp files.

Cheers, and thanks for your amazing work!

_Originally posted by @luckyspacetraveller in https://github.com/bmd-studio/stm32-for-vscode/issues/30#issuecomment-682208167_

**Comment by jortbmd** [comment]
This is fixed in the newest version so will close this issue.

**Comment by luckyspacetraveller** [comment]
@jortbmd Amazing work, thank you very much :)
