### ISSUE TITLE
Custom Programmer does not apply to STM32Make.make

### ISSUE THREAD

**Issue by btheobald** [bmd-studio/stm32-for-vscode#33]
In the configuration settings for this plugin there is the option to configure the programmer/interface config file used by OpenOCD. Changing this setting does not seem to change the generated makefile

In src/CreateMakefile.ts, 'interface/stlink.cfg' looks to be hardcoded during makefile creation, rather than referencing the configuration setting. 

```make
#######################################
# flash
#######################################
flash: $(BUILD_DIR)/$(TARGET).elf
\t${makeInfo.tools.openOCD ? makeInfo.tools.openOCD : 'openocd'} -f interface/stlink.cfg  -f target/${getTargetConfig(makeInfo.targetMCU)} -c "program $(BUILD_DIR)/$(TARGET).elf verify reset exit"
#######################################
# erase
#######################################
erase: $(BUILD_DIR)/$(TARGET).elf
\t${makeInfo.tools.openOCD ? makeInfo.tools.openOCD : 'openocd'} -f interface/stlink.cfg -f target/${getTargetConfig(makeInfo.targetMCU)} -c "init; reset halt; ${makeInfo.targetMCU} mass_erase 0; exit"
```

**Comment by jortbmd** [comment]
Hi thank you for opening an issue.
My apologies. You are correct I forgot to take that out in the production as it was an incomplete feature. However I just implemented this feature and pushed it to the marketplace so it should work now. As it is fixed with the new release I am closing the issue.
