### ISSUE TITLE
compilerPath lost on the second executing of STM32 build

### ISSUE THREAD

**Issue by tonilupi** [bmd-studio/stm32-for-vscode#47]
Hi, in advance thanks for your work guys.

I encounteres an issue on c_cpp_properties.json, with a fresh MX project the STM32 build command generate c_cpp_properties.json whith correct compilerPath 

"compilerPath": "C:\\VSARM\\GNU ARM EMBEDDED TOOLCHAIN\\10 2020-Q4-MAJOR\\BIN\\ARM-NONE-EABI-GCC.EXE"

But at second STM32 build execute the compilerPath change to NULL

 "compilerPath": null

I attach a .gif where you can view the case.

What do you think is happen?

Best regards

![Issue STM32 build](https://user-images.githubusercontent.com/36629167/106367902-5af81380-6346-11eb-9efd-633596ae232f.gif)

**Comment by jortbmd** [comment]
I have done some intensive refactoring over the past few months for version 3.0.0 this issue has been resolved. So I am closing it.
