### ISSUE TITLE
LIBDIR not correctly parsec or incorrectly named

### ISSUE THREAD

**Issue by RicoKirstein** [bmd-studio/stm32-for-vscode#48]
The LIBDIR variable is not parsed correctly from the makefile because it is named "libDirs" in your makefile parser instead of "libdir"

**Comment by jortbmd** [comment]
Hi,
Thank you for investigating and coming up with a solution! The library intergration was still on the roadmap but I had already taken some steps to make it work. For now I added the fix in a branch which will bring some new features to the table including library inclusion.

**Comment by jortbmd** [comment]
Version 3.0.0 fixes this issue and for this reason I am closing this. Thanks again for your help with this issue.
