### ISSUE TITLE
Add some buttons at the bottom

### ISSUE THREAD

**Issue by cccbug** [bmd-studio/stm32-for-vscode#50]
Hello,
If it possible to add such as build debug & flash button looks like 
![image](https://user-images.githubusercontent.com/52122620/111570894-b5f3a600-87e0-11eb-8290-3f4820830d2c.png)

There is source code，https://github.com/espressif/vscode-esp-idf-extension

Thanks.

**Comment by jortband** [comment]
Hi,
I was already working on something similar. For the next big update that I am finishing up I wanted to put the build and flash commands in the sidebar. As can be seen below. The idea is that I will also extend this menu further with some additional features after the current major update has been finished. Hope this is close enough to what you are looking for.
![new_stm_menu](https://user-images.githubusercontent.com/17765522/111596084-14af2480-87cd-11eb-8006-fe9438b69364.PNG)

**Comment by cccbug** [comment]
Ok，Thank you
