### ISSUE TITLE
Works only first Run

### ISSUE THREAD

**Issue by kipergrof** [bmd-studio/stm32-for-vscode#51]
Sorry but my english is not the best. 

When I use some task first time, ex.: "Flash STM" etc.. then works perfect, after i cant run other task (nothing happens). This error occurs when I set up the user paths and workspace at sametime in extension settings. I have read this error among previous issues. I hope, you unerstand what i want to tell, and i could help.

Delete user path and work extension.
![image](https://user-images.githubusercontent.com/25442201/114221854-20c27800-996e-11eb-92ac-0037594858fc.png)

**Comment by jortbmd** [comment]
There was an issue with adding paths and the like to the extension. This should be resolved in version 3.0.0 which will be released in a couple of days. Should this issue persist please open a new issue.
