### ISSUE TITLE
Compile warnings and errors not appearing in Problems window

### ISSUE THREAD

**Issue by TomN7** [bmd-studio/stm32-for-vscode#64]
Any compilation warnings from make are not appearing in the problems window. The only warnings or errors that appear are from intellisense and can be false positives.

I've done some tests and if the tasks are adjusted to call the command line tools directly (replacing "${command:stm32-for-vscode.build}" etc.) then any problems are matched fine using the built-in $gcc matcher. It appears for some reason the intermediate script is preventing the problem matcher from looking at the output log.

**Comment by jortbmd** [comment]
Hi thank you for notifying me. I have fixed this in V3.0.5 and now the compilation output will show up in the problems window.
