### ISSUE TITLE
Is there any configure can boot in sram

### ISSUE THREAD

**Issue by monody1** [bmd-studio/stm32-for-vscode#66]

**Comment by jortbmd** [comment]
Hi, this is a very unusual request. I would have no idea how to do this and it seems more STM32 chip related than something to do with STM32 for VSCode. So I am closing this issue.
On the topic of booting from SRAM I have never seen it done before and it does seem like it is opening a can of worms when you want to actually do this, as you can never really be sure the SRAM has valid data when you have a power loss.
