### ISSUE TITLE
Could you update the extension on vscode marketplace

### ISSUE THREAD

**Issue by utkarshsethi** [bmd-studio/stm32-for-vscode#67]
The marketplace has an old version 2.2.4 which doesn't even provide the ST button mentioned in the instructions.

**Comment by jortbmd** [comment]
Yes! The extension was in an open beta, due to some major changes. However this has been finished and I was just finishing some final testing. The new extension is on the marketplace now.

**Comment by utkarshsethi** [comment]
Is there a forum for this extension? or is thee issues page the best place to ask??
