### ISSUE TITLE
An error when building a project with space symbol in name

### ISSUE THREAD

**Issue by sinkapoy** [bmd-studio/stm32-for-vscode#69]
If project target contains " ", make gives something like
`make: *** No rule to make target '<last word of the target>.hex', needed by 'all'.  Stop.`
`make: *** Waiting for unfinished jobs....`
`The terminal process "/bin/bash '-c', '"make" -j16 -f STM32Make.make '" terminated with exit code: 2.`

**Comment by jortbmd** [comment]
Hi. I will look into this and come up with a quick fix when I have time this week. For now the solution would be to change the target name in the STM32-for-VSCode.config.yaml file to something without a space.

**Comment by jortbmd** [comment]
This has been fixed in the new v3.0.7 version. You need to delete your launch.json and task.json files and let them regenerate for it to work.
