### ISSUE TITLE
Builds, specifically c++, is significantly larger

### ISSUE THREAD

**Issue by bhatasaka** [bmd-studio/stm32-for-vscode#84]
When using the extension to generate code, the final generated elf file comes out larger when compared to the Makefile that STM32CubeMx generates. For example, here is what the CubeMx file generates for an almost freshly generated project:
```
   text    data     bss     dec     hex filename
   1780      12    1564    3356     d1c build/test_no_init.elf
```
Here is what the extension generates:
```
c:/program files (x86)/gnu arm embedded toolchain/10 2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld.exe: build/test_no_init.elf section `._user_heap_stack' will not fit in region `RAM'
c:/program files (x86)/gnu arm embedded toolchain/10 2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld.exe: region `RAM' overflowed by 600 bytes
```
If I change the stack and heap min sizes in the `.ld` file to 128 bytes, this is what the extension produces:

```
   text    data     bss     dec     hex filename
   2188    1088     292    3568     df0 build/test_no_init.elf
```
Here is what the Mx file generates with the new stack and heap min sizes:
```
   text    data     bss     dec     hex filename
   1780      12     284    2076     81c build/test_no_init.elf
```

And here is what the extension generates for C++:
```
   text    data     bss     dec     hex filename
   6644    1088     292    8024    1f58 build/test_no_init.elf
```

The flash and ram usage is significantly higher. Specifically the RAM and the C++ flash usage as the extension build of a blank project won't  fit on the MCU. I tried to objdump and look at the differences between the elf files, as well as look at the differences between the makefiles, however I don't have much experience and cannot make sense of what is generating so much larger code. I tried creating the same project in STM32CubeIDE and it is able to generate significantly smaller sections for both C and C++.

My problem specifically is that I want to use C++ but I don't want to be forced to use CubeIDE. Otherwise I would probably just use the Mx generated Makefile and C.
The board I am using is the NUCLEO-L011K4.
Generating the project using STM32CubeMX I am following the guidelines specified by the extension.
 In addition, the following settings:
- all peripherals initialized to default - NO
- Set all free pins as analog (to optimize the power consumption)
- GPIO, RCC set to use LL libraries rather than HAL

And of course this is easy to test out as you don't actually need any hardware to do so.

I really appreciate how easy this extension makes it to use VSCode with my home projects! It is just very unfortunate that it won't work for this MCU. I have a bunch of these tiny chips (couldn't get the ones I wanted due to the chip shorted) and am trying to stretch their limited space as I can.

Thanks for all the work and your contributions with this extension!

**Comment by jortbmd** [comment]
Hi!

This is an interesting case. As the default settings for this particular platform are all optimised for low memory usage, however due to the optimisation some things need to be done before it is as optimised as the cubeMX version.

For c you can change the STM32-for-VSCode.config.yaml to get the same size. To do this change  the assembly flags of -specs=nosys.specs to -specs=nano.specs e.g.:
```YAML
assemblyFlags: 
  - -specs=nano.specs
 ```
 This should already solve the issues for c projects.
 
 For c++ it is a tiny bit more involved. You also need to change the assembly flags to -specs=nano.specs, however the standard libraries need to be changed from c to  stdc++. E.g. that specific section of STM32-for-VSCode.config.yaml will look like this:
 ```YAML
 assemblyFlags: 
  - -specs=nano.specs


# libraries to be included. The -l prefix to the library will be automatically added.
# Mind that non standard libraries should have a path to their respective directory.
libraries: 
  - m
  - stdc++
  - supc++
 ```
 
However when doing this some system calls will not be implemented, which is why CubeIDE includes them in Core/Src.
However this can be easily fixed by including a syscalls.c file. To do this create a syscalls.c file in Core/Src and copy the following code:
```C
/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>


/* Variables */
extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void) __attribute__((weak));


char *__env[1] = { 0 };
char **environ = __env;


/* Functions */
void initialise_monitor_handles()
{
}

int _getpid(void)
{
	return 1;
}

int _kill(int pid, int sig)
{
	errno = EINVAL;
	return -1;
}

void _exit (int status)
{
	_kill(status, -1);
	while (1) {}		/* Make sure we hang here */
}

__attribute__((weak)) int _read(int file, char *ptr, int len)
{
	int DataIdx;

	for (DataIdx = 0; DataIdx < len; DataIdx++)
	{
		*ptr++ = __io_getchar();
	}

return len;
}

__attribute__((weak)) int _write(int file, char *ptr, int len)
{
	int DataIdx;

	for (DataIdx = 0; DataIdx < len; DataIdx++)
	{
		__io_putchar(*ptr++);
	}
	return len;
}

int _close(int file)
{
	return -1;
}


int _fstat(int file, struct stat *st)
{
	st->st_mode = S_IFCHR;
	return 0;
}

int _isatty(int file)
{
	return 1;
}

int _lseek(int file, int ptr, int dir)
{
	return 0;
}

int _open(char *path, int flags, ...)
{
	/* Pretend like we always fail */
	return -1;
}

int _wait(int *status)
{
	errno = ECHILD;
	return -1;
}

int _unlink(char *name)
{
	errno = ENOENT;
	return -1;
}

int _times(struct tms *buf)
{
	return -1;
}

int _stat(char *file, struct stat *st)
{
	st->st_mode = S_IFCHR;
	return 0;
}

int _link(char *old, char *new)
{
	errno = EMLINK;
	return -1;
}

int _fork(void)
{
	errno = EAGAIN;
	return -1;
}

int _execve(char *name, char **argv, char **env)
{
	errno = ENOMEM;
	return -1;
}

```

This should fix the issue and reduce the size.

I will leave the issue open for now. I am still considering if this is something I should account for or more or less and edge case for C++, however the makefile of CubeMX does seem to include nano instead of the nosys specs. For now the extension has it hardcoded to nosys, but this might be nice to extract for these kinds of cases.

**Comment by bhatasaka** [comment]
Thanks so much for the detailed and quick reply! It worked great for C - actually generated a .text section a few bytes smaller than the Makefile.
I think I may be doing something wrong as I am still getting a larger size with C++,
here is with C:
```
   text    data     bss  
   2176      12    1564 
```
and C++ with the changes mentioned above:
```
   text    data     bss     
   6496     112    1568 
```

and C++ from CubeIDE results in:
- .text = 3.92 KB
- .data = 4 B
- .bss = 28 B

I'm honestly not sure why the results are different between CubeIDE and Makefile with the same settings, but that is what I'm seeing regardless. I clearly have a lot to learn about gcc!
I'm using slightly different settings for CubeMX than I did in the original post:
- All peripherals initialized to default - yes
- HAL set to LL for GPIO, RCC, and USART
- 
Your solution works well enough for me, I can fit what I need to into flash and RAM so this is more of a response as to my results with the above changes. Let me know if you want more info.
Thanks!

**Comment by ARNik** [comment]
This made my C++ smaller:

```yaml
cxxFlags: 
  - -fno-rtti
  - -fno-exceptions
```

**Comment by jortbmd** [comment]
@ARNik  yes seems to make a huge difference. In comparison:
```
C++ Default
text    data     bss     dec     hex filename
10664     100     740   11504    2cf0 build/project_size_test.elf

C++ -fno-rtti & -fno-rtti
text    data     bss     dec     hex filename
6448      20     420    6888    1ae8 build/project_size_test.elf

C standard
text    data     bss     dec     hex filename
6448      20     420    6888    1ae8 build/project_size_test.elf
```

Seems like the rtti and exceptions were the culprits. Seems like a good default to add these flags. I will possibly integrate this in a next release.
