### ISSUE TITLE
Missing rule for adc.o

### ISSUE THREAD

**Issue by ayleenw** [bmd-studio/stm32-for-vscode#85]
Getting this error on Windows 10:
MAKE.EXE: *** No rule to make target `build/adc.o', needed by `build/F0_VSC_TEST.elf'.  Stop.
(Project compiles on MacOS and Linux).

File "adc.c" is present and listed in the Makefile:
C_SOURCES =  \
Core/Src/adc.c \
Toolchain is installed (paths in settings.json):
    "stm32-for-vscode.armToolchainPath": "C:\\PROGS\\SYSGCC\\ARM-EABI\\BIN",
    "cortex-debug.armToolchainPath": "C:\\PROGS\\SYSGCC\\ARM-EABI\\BIN",
    "cortex-debug.openocdPath": "C:\\PROGS\\OPENOCD\\BIN\\OPENOCD.EXE",
And in c_cpp-properties.json:
    "compilerPath": "C:\\PROGS\\SYSGCC\\ARM-EABI\\BIN\\ARM-NONE-EABI-GCC.EXE"

**Comment by jortbmd** [comment]
That seems like everything is in order and it should compile

Can you perhaps install the stm32 vscode build tools just to make sure it is not due versioning of tools? If you press cmd/ctrl+shift+p you can type in STM32: install and you should find the command to install all the build tools.

**Comment by ayleenw** [comment]
Unfortunately no change after (re)installing the build tools in the mentioned way. The automatic installation had failed in the first place, thats why I installed openocd, make and the arm gcc manually. Now when I invoke the command to install the build tools, it reports back (with no errors):

> Executing task: & \"c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\bmd.stm32-for-vscode\node\node-v17.0.1-win-x64\npx\" xpm install --global @xpack-dev-tools/openocd@latest <
> Executing task: & \"c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\bmd.stm32-for-vscode\node\node-v17.0.1-win-x64\npx\" xpm install --global @xpack-dev-tools/arm-none-eabi-gcc@latest <

But nothing about make.

**Comment by jortbmd** [comment]
Thank you for checking!
Just to check I made an empty project for the STM32F072B Discovery board and one for the nucleo board. Both compile perfectly fine on my windows machine. Can I ask you what version of make you are running? That is the only thing I can currently think of which still might be different.

**Comment by ayleenw** [comment]
Thanks for that hint! I had version 3.82. Now I installed 4.3 via Cygwin and it works. Thank you very much!

**Comment by jortbmd** [comment]
Great to hear that it is resolved! For now I am closing this issue. Should you have any other issues or feature requests feel free to open up another issue.
