### ISSUE TITLE
Add folder filter for makefile generation

### ISSUE THREAD

**Issue by Bonnee** [bmd-studio/stm32-for-vscode#9]
I have a stm32 project that links to a submodule containing cpp code and when I run a build, stm32-for-vscode includes those cpp files in the makefile, breaking the build process.
I'm suggesting to add a filter configuration to select excluded directories inside the project

**Comment by jortbmd** [comment]
Hi thanks for opening an issue. I will take this into account when doing an upgrade as I think it would be a helpful feature. It will probably result in an .stmignore file using glob patterns for file or folder exclusion.

**Comment by jortbmd** [comment]
Added a new .stmignore functionality which allows you to use glob patterns to ignore files. It is in the current release.
